process.roles=broker,controller
node.id=1
controller.quorum.voters=1@localhost:9093

# Define listeners
listeners=PLAINTEXT://:9092,CONTROLLER://:9093
advertised.listeners=PLAINTEXT://kafka-production-e850.up.railway.app:9092

# Tell Kafka what protocol CONTROLLER uses
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

# Required for KRaft
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER

log.dirs=/tmp/kraft-combined-logs
